code_quality:
    image: docker:stable
    variables:
      DOCKER_DRIVER: overlay2
    allow_failure: true
    services:
      - docker:stable-dind
    script:
      - docker run
          --env SOURCE_CODE="$PWD"
          --volume "$PWD":/code
          --volume /var/run/docker.sock:/var/run/docker.sock
          "registry.gitlab.com/gitlab-org/ci-cd/codequality" /code
    artifacts:
      reports:
        codequality: gl-code-quality-report.json
  